### ISSUE TITLE
Size of input and output images

### ISSUE THREAD

**Issue by zhangyupeng123** [jiwoogit/StyleID#12]
Does the size of the input and output images have to be fixed, or can the original content image size be maintained?

**Comment by zhangyupeng123** [comment]
@jiwoogit Is it possible to keep the original size of the image after style transfer during inference?

**Comment by jiwoogit** [comment]
I think that, if your input is larger than 512, it is hard to maintain the original size in our project. However, it may be possible if you apply our method to another high-resolution image diffusion model that handles larger input images.

**Comment by zhangyupeng123** [comment]
Sure, I understand. I have a small question: Does using the stable diffusion always mean that the size of generated image is fixed by the stable diffusion model?

**Comment by zhangyupeng123** [comment]
ok~Thank you!
