### ISSUE TITLE
About evaluation metric

### ISSUE THREAD

**Issue by sherlhw** [jiwoogit/StyleID#16]
Is there any implementation code for the Content Feature Structural Distance (CFSD) mentioned in this paper？

**Comment by jiwoogit** [comment]
Yes, you can implement CFSD using the` eval_artfid.py` file. The specific implementation code for CFSD mentioned in the paper can be found at the following link:

https://github.com/jiwoogit/StyleID/blob/3c2995f467c3cb7ea029a858ef5a79651488e373/evaluation/eval_artfid.py#L420

**Comment by sherlhw** [comment]
Thanks！
