### ISSUE TITLE
can you provide diffusers' version?

### ISSUE THREAD

**Issue by FlyingCan** [jiwoogit/StyleID#2]
Hello, I encountered a problem while replicating your code using diffusers. The gamma parameter has almost no effect. I have repeatedly checked my code but it has not been resolved. Can you provide a reproduction of the diffusers version?    
 beta is the attention scale you mentioned in paper
q[:num_heads,...] means content querys,  , q[num_heads:2*num_heads,...] means cs querys
key[2*num_heads:,...]  means style key,

  def attn_batch(self, q, k, v, sim, attn, is_cross, place_in_unet, num_heads, beta=1.,**kwargs):
      """
      Performing attention for a batch of queries, keys, and values
      """

      sim = beta * torch.einsum("b i d, b j d -> b i j", q, k) * kwargs.get("scale")
      attn = sim.softmax(-1)
      out = torch.einsum("b i j, b j d -> b i d", attn, v)
      out = rearrange(out, '(b h) n d -> b n (h d)', h=num_heads)
      return out
def forward(self, q, k, v, sim, attn, is_cross, place_in_unet, num_heads, **kwargs):
        """
        Attention forward function
        """
        if is_cross or self.cur_step not in self.step_idx or self.cur_att_layer // 2 not in self.layer_idx:
            return super().forward(q, k, v, sim, attn, is_cross, place_in_unet, num_heads, **kwargs)
    #normal operation:
        out = self.attn_batch(q, k, v, sim, attn, is_cross, place_in_unet, num_heads, **kwargs)
    
        # style injection op
        q_cs = self.gamma * q[:num_heads,...] + ( 1 - self.gamma ) * q[num_heads:2*num_heads,...]
        out_cs = self.attn_batch(q_cs, k[2*num_heads:,...], v[2*num_heads:,...], sim, attn, is_cross, place_in_unet, num_heads,beta=self.beta,**kwargs)
        out[1:2,...] = out_cs 
        return out
![step_0_beta_1 5_layer6-checkpoint](https://github.com/jiwoogit/StyleID/assets/91962377/3c552b14-a79a-4817-9f10-9d51ac433508)

**Comment by hse1032** [comment]
Hi, 

we tested the StyleID with diffuser, and validated that it still works well.
(Results are shown below)

I recommend to upscale the input image size to 512x512, which is the default setting of stable diffusion.

(gamma=0.1, 0.3, 0.5)
![image](https://github.com/jiwoogit/StyleID/assets/115209649/3f278989-1a6c-4740-9caf-ce8c291ff5ea)

or I will upload the diffuser implementation of StyleID in this repository,
so check the implementation difference after uploading.

Thanks,

**Comment by hse1032** [comment]
We upload StyleID implementation based on diffusers in "diffusers_implementation/" in this repository,
please check this implementation.

Thanks for your interest!
