### ISSUE TITLE
Papers in details

### ISSUE THREAD

**Issue by JustinKai0527** [jiwoogit/StyleID#3]
Hi, thanks for this wonderful work! Your work is achieving astonishing results.. There is one question about the color tone you discuss on section 4.2 in the arxiv paper. In the below picture, the **Q K V** are feed from the style img feature, so the output I thought only depends on the style img, so when the content img feature have access in this process. I think is the section 4.1 blend query(second picture) doing this? thx!
![image](https://github.com/jiwoogit/StyleID/assets/103019623/f6d86976-c166-4ec4-9711-f392b2886a0c)
![image](https://github.com/jiwoogit/StyleID/assets/103019623/2b1b3db7-341b-44d8-bcbe-ba8b0cda8500)

**Comment by jiwoogit** [comment]
Thank you for your interest!

I think that there might be some confusion about the details of the ablated setting (b).

To generate the results of (b), we didn't use the Q, K, V self-attention features of the content images, and we didn't use query blending.

In other words, we injected the feature of the style images for all self-attention layers: $Q^{cs}_t = Q^{s}_t$, $K^{cs}_t = K^{s}_t$, $V^{cs}_t = V^{s}_t$.

Thus, the generated results are similar to those of the style images, but they don't change in terms of the **color tone**.

So, we were motivated to modify the initial latent noise ($z^c_T$).

Feel free to ask if you need further clarification.

**Comment by JustinKai0527** [comment]
okay I got it, thank you for the response.

**Comment by jiwoogit** [comment]
In the Stable Diffusion architecture, the latent noise ($z^c_T$) may influence the output through two paths:

1. Skip connections in the U-Net architecture.
2. Residual connections in the self-attention layers: $\phi_\text{final}=\phi+\phi_\text{out}$.

Hope this helps! Thank you.

**Comment by jiwoogit** [comment]
In the Stable Diffusion architecture, the latent noise ($z^c_T$) may influence the output through two paths:

1. Skip connections in the U-Net architecture.
2. Residual connections in the self-attention layers: $\phi_\text{final}=\phi+\phi_\text{out}$.

Hope this helps! Thank you.

**Comment by JustinKai0527** [comment]
thx for the quickly reponse, your work is doing so well
