### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory: '/root/code/StyleID-main/data/sty/.ipynb_checkpoints'

### ISSUE THREAD

**Issue by Lcgcl** [jiwoogit/StyleID#5]
It a promising job, but I have some errors.
IsADirectoryError: [Errno 21] Is a directory: '/root/code/StyleID-main/data/sty/.ipynb_checkpoints'

**Comment by jiwoogit** [comment]
I think the error is likely due to the your conversion of the code to Python notebook format.
Please check the notebook configuration settings.

**Comment by cccjw0** [comment]
I met the same problem when I run the project on a Cloud Server while the terminal is opened through jupyter notebook. But when I open the project with VScode via ssh, and delete the directory .ipynb_ckpt which is unvisiable on cloud, the problem is solved.
