### ISSUE TITLE
It seems my result is incorrect.

### ISSUE THREAD

**Issue by Amo5** [jiwoogit/StyleID#8]
content img:
![horse](https://github.com/jiwoogit/StyleID/assets/41940277/087ca3a6-c620-4b9c-b0ff-26642ddb0b1c)
style img:
![crystal_bunny](https://github.com/jiwoogit/StyleID/assets/41940277/a29f5b48-eb31-4990-bf3f-c0efdc850652)
stylized img:
![image](https://github.com/jiwoogit/StyleID/assets/41940277/3cbc58c7-6a93-4f8c-b1b0-fc77baba8827)

My command line is,
python run_styleid_diffusers.py --cnt horse.jpg --sty crystal_bunny.png

**Comment by hse1032** [comment]
Hi,
we test your images with default settings and obtain the result as below.

![stylized_image](https://github.com/jiwoogit/StyleID/assets/115209649/d9e45f0c-1f9d-40ab-b946-be39584e6896)

My command line is,
python3 run_styleid_diffusers.py --sty_fn=crystal_bunny.png --cnt_fn=horse.jpg

but I additionally resize your images into the resolution of (512, 512).
